import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ProductService } from '../../services/product';
import { Product } from '../../models/product';

@Component({
  selector: 'app-product-create',
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './product-create.html',
})
export class ProductCreate {
  urlInput: string = '';
  errorMessage: string | null = null;
  isSubmitting: boolean = false;

  constructor(
    private productService: ProductService,
    private router: Router,
  ) {}

  onSubmit(form: NgForm): void {
    if (form.invalid) return;

    this.isSubmitting = true;
    this.errorMessage = null;

    // Prepare the product data for creation, excluding the 'id' since it will be generated by the backend
    const newProductData: Omit<Product, 'id'> = {
      name: form.value.name,
      price: form.value.price,
      category: form.value.category,
      imageUrl: form.value.imageUrl,
      description: form.value.description,
    };

    this.productService.createProduct(newProductData).subscribe({
      next: () => {
        this.isSubmitting = false;
        alert('Product created successfully!');
        this.router.navigate(['/pages/products']);
      },
      error: (err) => {
        this.isSubmitting = false;
        // Generic error handling for the UI
        if (err.status === 401 || err.status === 403) {
          this.errorMessage = 'You must be logged in as an admin to perform this action.';
        } else if (err.status === 0) {
          this.errorMessage = 'Server is unreachable. Please check your backend.';
        } else {
          this.errorMessage = 'Failed to create product. Please check your inputs and try again.';
        }
      },
    });
  }
}
